package com.muziqiu.payrollapplication.model;

import java.util.Date;

public class TimeReport {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column time_report.id
     *
     * @mbg.generated Sun Feb 14 11:02:14 EST 2021
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column time_report.date
     *
     * @mbg.generated Sun Feb 14 11:02:14 EST 2021
     */
    private Date date;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column time_report.hours_worked
     *
     * @mbg.generated Sun Feb 14 11:02:14 EST 2021
     */
    private Double hoursWorked;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column time_report.job_group
     *
     * @mbg.generated Sun Feb 14 11:02:14 EST 2021
     */
    private String jobGroup;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column time_report.employee_id
     *
     * @mbg.generated Sun Feb 14 11:02:14 EST 2021
     */
    private Integer employeeId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column time_report.report_id
     *
     * @mbg.generated Sun Feb 14 11:02:14 EST 2021
     */
    private Integer reportId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column time_report.id
     *
     * @return the value of time_report.id
     * @mbg.generated Sun Feb 14 11:02:14 EST 2021
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column time_report.id
     *
     * @param id the value for time_report.id
     * @mbg.generated Sun Feb 14 11:02:14 EST 2021
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column time_report.date
     *
     * @return the value of time_report.date
     * @mbg.generated Sun Feb 14 11:02:14 EST 2021
     */
    public Date getDate() {
        return date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column time_report.date
     *
     * @param date the value for time_report.date
     * @mbg.generated Sun Feb 14 11:02:14 EST 2021
     */
    public void setDate(Date date) {
        this.date = date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column time_report.hours_worked
     *
     * @return the value of time_report.hours_worked
     * @mbg.generated Sun Feb 14 11:02:14 EST 2021
     */
    public Double getHoursWorked() {
        return hoursWorked;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column time_report.hours_worked
     *
     * @param hoursWorked the value for time_report.hours_worked
     * @mbg.generated Sun Feb 14 11:02:14 EST 2021
     */
    public void setHoursWorked(Double hoursWorked) {
        this.hoursWorked = hoursWorked;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column time_report.job_group
     *
     * @return the value of time_report.job_group
     * @mbg.generated Sun Feb 14 11:02:14 EST 2021
     */
    public String getJobGroup() {
        return jobGroup;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column time_report.job_group
     *
     * @param jobGroup the value for time_report.job_group
     * @mbg.generated Sun Feb 14 11:02:14 EST 2021
     */
    public void setJobGroup(String jobGroup) {
        this.jobGroup = jobGroup;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column time_report.employee_id
     *
     * @return the value of time_report.employee_id
     * @mbg.generated Sun Feb 14 11:02:14 EST 2021
     */
    public Integer getEmployeeId() {
        return employeeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column time_report.employee_id
     *
     * @param employeeId the value for time_report.employee_id
     * @mbg.generated Sun Feb 14 11:02:14 EST 2021
     */
    public void setEmployeeId(Integer employeeId) {
        this.employeeId = employeeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column time_report.report_id
     *
     * @return the value of time_report.report_id
     * @mbg.generated Sun Feb 14 11:02:14 EST 2021
     */
    public Integer getReportId() {
        return reportId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column time_report.report_id
     *
     * @param reportId the value for time_report.report_id
     * @mbg.generated Sun Feb 14 11:02:14 EST 2021
     */
    public void setReportId(Integer reportId) {
        this.reportId = reportId;
    }
}